services:
    shoppingapi: 
        build:
            context: .
            dockerfile: Dockerfile
        image: shoppingapi
        container_name: shoppingapi
        ports:
        - "7000:8080"
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        networks:
        - my_network
networks:
    my_network:
     driver: bridge